### ISSUE TITLE
Bug in corda-training-solutions/src/main/kotlin/net/corda/training/contract/IOUContract.kt

### ISSUE THREAD

**Issue by mikecave** [roger3cev/corda-training-solutions#18]
requireThat required on line 93. I can't create a pull request on this repo for some strange reason otherwise I would have fixed it myself.

**Comment by amoothart** [comment]
Thanks @mikecave for calling this out. The code runs fine as is but I've added requireThat for completeness.

**Comment by mikecave** [comment]
I'm not sure how it runs fine for you without, it didn't run for me or others on the course and the syntax clearly looks incorrect?

**Comment by amoothart** [comment]
Do you have error message still?
